@startuml

<style>
document {
  BackGroundColor transparent
}
element {
  FontColor #0969DA
  LineColor #0969DA
  BackGroundColor transparent
  FontSize 12
  RoundCorner 0
}
</style>

participant "Código cliente" as PC
participant "//Stub//" as SC
participant "OS local" as LOS
participant "OS remoto" as ROS
participant "//Skeleton//" as SS
participant "Servidor" as S

PC ->> SC : 1: call(params)
SC ->> SC : 2: msg = marshal(params)
SC ->> LOS : 3: send(msg)
LOS ->> ROS : 4: send(msg)
ROS ->> SS : 5: receive(msg)
SS ->> SS : 6: params = unmarshal(msg)
SS ->> S : 7: call(params)

@enduml
